### ISSUE TITLE
Enabling yarn test in Travis

### ISSUE THREAD

**Issue by eirikdahlen** [eirikdahlen/TDT4290_Aqeous#84]
As of now, Travis is skipping the `yarn test` command because the test is failing. 
This should be fixed for future development.

**Comment by eirikdahlen** [comment]
Could this be a solution?
https://stackoverflow.com/questions/56091343/typeerror-window-require-is-not-a-function

**Comment by Trebua** [comment]
Nope..

Been trying for a long time now with no progress. It seems like the preload script must be run before tests are run (which it is not now), or create a jest mockup of window or remote or something
